"""initial_platform_schema

Revision ID: 30199b902d56
Revises: 
Create Date: 2026-03-23 22:40:39.421753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30199b902d56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('scenario_set', sa.String(length=128), nullable=True),
    sa.Column('config_hash', sa.String(length=128), nullable=True),
    sa.Column('execution_config', sa.JSON(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('artifacts_dir', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('run_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('persona_display_name', sa.String(length=256), nullable=False),
    sa.Column('persona_source_file', sa.String(length=256), nullable=True),
    sa.Column('persona_variables', sa.JSON(), nullable=True),
    sa.Column('run_label', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('criterion_scores', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_items_persona_display_name'), 'run_items', ['persona_display_name'], unique=False)
    op.create_index(op.f('ix_run_items_run_id'), 'run_items', ['run_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_item_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('criterion_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_item_id'], ['run_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_run_item_id'), 'findings', ['run_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_run_item_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_run_items_run_id'), table_name='run_items')
    op.drop_index(op.f('ix_run_items_persona_display_name'), table_name='run_items')
    op.drop_table('run_items')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
