"""add_run_progress_fields

Revision ID: ae88bd30f2aa
Revises: 30199b902d56
Create Date: 2026-03-25 22:16:47.868008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae88bd30f2aa'
down_revision: Union[str, Sequence[str], None] = '30199b902d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('total_items', sa.Integer(), nullable=False, server_default=sa.text("0")))
    op.add_column('runs', sa.Column('processed_items', sa.Integer(), nullable=False, server_default=sa.text("0")))
    op.add_column('runs', sa.Column('failed_items', sa.Integer(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'failed_items')
    op.drop_column('runs', 'processed_items')
    op.drop_column('runs', 'total_items')
    # ### end Alembic commands ###
